### ISSUE TITLE
Support parameters on queries

### ISSUE THREAD

**Issue by laurocaetano** [liveforeverx/mariaex#10]
Hi!

It doesn't seem that Mariaex supports parameters on queries such as documented here: https://github.com/liveforeverx/mariaex/blob/master/lib/mariaex/connection.ex#L112

```elixir
iex(1)> {:ok, p} = Mariaex.Connection.start_link(username: "root", database: "ecto_test")
{:ok, #PID<0.95.0>}
iex(2)> Mariaex.Connection.query(p, "CREATE TABLE test_1 (id serial, title text)")
:ok
iex(3)> Mariaex.Connection.query(p, "SELECT id FROM test_1 WHERE title like $1", ["%my%"])
{:error,
 %Mariaex.Error{mariadb: %{code: 1054,
    message: "Unknown column '$1' in 'where clause'"}, message: nil}}
```

Is there anything we can do to help fixing it? Thanks :)

**Comment by jquadrin** [comment]
hmm looks like encoders need some work, I'm looking into this. @liveforeverx what needs to be done?

**Comment by liveforeverx** [comment]
Yes, it wasn't implemented yet and documentation was copied from postgrex.

I've started implementing it today, and will continue(and I think end implementation on Saturday/Sunday ). Do not exactly, what help can be needed. And, sorry for delay.

I'll write here, how I will implement it, and if somebody know better solution(or, I'm doing something wrong) for it, I would appreciate for helping/clarifying. I will use [prepared statements](http://dev.mysql.com/doc/internals/en/prepared-statements.html) for it , that is seems to be exactly, what needed(right?). The mysql syntax is different from postgres, as postgres uses '$1' and MySQL uses '?' for parameters. Is it a problem or does something more complicated, if it will stay '?'?

**Comment by laurocaetano** [comment]
@liveforeverx nice :)

Thanks for the fast feedback :heart:

**Comment by liveforeverx** [comment]
Initial work is done, from here it can be diveded. Basic support is added, not all types are supported at the moment. There some work on types needed.

**Comment by laurocaetano** [comment]
I think it can be closed now since the basic support is done. 
Thanks :)
