### ISSUE TITLE
Fix timeout bug

### ISSUE THREAD

**Issue by josevalim** [liveforeverx/mariaex#11]
This client has the same bug as postgrex had which is relying on timeouts and returning :normal when it isn't really supposed to. I have fixed this in postgrex, I recommend going through those changes and apply them to mariaex too:

https://github.com/ericmj/postgrex/compare/6908762d3a7f4b6cd82ba5841f49f40ee10dde16...a01685682fb3ffd79496eb3ad009f94e8a23ef2f

:)

**Comment by josevalim** [comment]
In short words, we have removed the timeout logic and we stopped returning :normal exits (except for the stop call).

**Comment by ericmj** [comment]
Another place where we kept {:stop, :normal} was in the connect call because it is only called from the init function which will error anyway.
