### ISSUE TITLE
Improve error message we can't connect to the database

### ISSUE THREAD

**Issue by josevalim** [liveforeverx/mariaex#6]
Today, if you pass bad credentials when starting the connection to the database, it fails with a case clause error on :tcp_closed. We should instead handle this case and return a proper error, saying we were unable to connect to the database.

**Comment by josevalim** [comment]
Can we please reopen this one? All we are going to say in this case is that the tcp connection is closed, which is an improvement, but I would rather say we can't authenticate in the first place. Otherwise users will be clueless to why the connection was closed. :)

**Comment by liveforeverx** [comment]
It was occasionally closed.

**Comment by josevalim** [comment]
Thanks @jquadrin and @liveforeverx !

**Comment by liveforeverx** [comment]
If nobody working on errors at the moment, I'll tackle this.

**Comment by jquadrin** [comment]
@liveforeverx I just changed the message, feel free to close if you are working on it already

**Comment by josevalim** [comment]
The current message is fine. TCP can be closed in other situations. We just need to explicitly check those for authentication errors. I think postgrex even has specific tests for this kind of stuff. :)

**Comment by liveforeverx** [comment]
So, pushed to master the code, that tests false user/database and shows error. Next step to test the connection with password/false password, will do it somewhere tomorrow.

Try to find the test on postgrex, but didn't find, where it tested... @josevalim , see this line: https://github.com/liveforeverx/mariaex/blob/master/lib/mariaex/connection.ex#L64 sometimes it happens, that tcp_closed will got and process terminated(with the linked starter process), before starter process get error. This lead to undefined behaviour, if trap_exit set to false:

```elixir
iex(1)> Mariaex.Connection.start_link(database: "non_existing")
** (EXIT from #PID<0.104.0>) %Mariaex.Error{mariadb: nil, message: "connection closed"}

Interactive Elixir (1.1.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
22:52:39.904 [error] GenServer #PID<0.106.0> terminating
Last message: {:tcp_closed, #Port<0.15965>}
State: %{backend_key: nil, opts: [hostname: "localhost", password: nil, username: "dima", database: "non_existing"], parameters: %{}, queue: {[], []}, rows: [], seqnum: 0, sock: {Mariaex.Connection.Tcp, #Port<0.15965>}, sock_mod: Mariaex.Connection.Tcp, state: :running, statement: nil, tail: "", types: :types_removed}
** (exit) %Mariaex.Error{mariadb: nil, message: "connection closed"}
iex(1)> Mariaex.Connection.start_link(database: "non_existing")
{:error,
 %Mariaex.Error{mariadb: %{code: 1044,
    message: "Access denied for user ''@'localhost' to database 'non_existing'"},
  message: "Access denied for user ''@'localhost' to database 'non_existing'"}}
```

Do not tested it on postgrex, but it can have the same problem.

**Comment by liveforeverx** [comment]
So, tested with master(fix password authorization):

```elixir
iex> Mariaex.Connection.start_link(username: "pass", password: "wrong_pass", database: "ecto_test")
{:error,
 %Mariaex.Error{mariadb: %{code: 1045,
    message: "Access denied for user 'pass'@'localhost' (using password: YES)"},
  message: nil}}

iex> Mariaex.Connection.start_link(username: "pass", password: "pass", database: "ecto_test")
{:ok, #PID<0.106.0>}
```

And, there are tests for all other cases(false user | database, impossible to connect to database(tcp error)) here: https://github.com/liveforeverx/mariaex/blob/master/test/start_test.exs

**Comment by josevalim** [comment]
Beautiful!

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by liveforeverx** [comment]
I think, the issue can be closed for a long time.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
